version: "3.3"

services:
  db:
    image: mysql
    container_name: db
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - "./db/scripts/auth.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/scripts/courses.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks: 
      - database

  service.auth:
    container_name: service.auth
    build: service.auth/
    command: 
      "./main \
      -port=5050 -sk=triangleIsBestFigure"
    ports: 
      - 5050:5050
    depends_on:
      - db
    networks: 
      - database

  service.courses:
    container_name: service.courses
    build: service.courses/
    command: 
      "./main" \
      -port=5051 -sk=triangleIsBestFigure"
    ports: 
    - 5051:5051
    depends_on: 
      - db
    networks: 
    - database
    
networks: 
  database:
    driver: "bridge"