version: "3.3"

services:
  service.auth.db:
    image: mysql
    container_name: service.auth.db
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks: 
      - authnet

  service.auth:
    container_name: service.auth
    build: service.auth/
    command: 
      "./main -dbUser=docker -dbPassword=docker \
      -network=service.auth.db:3306 -dbName=auth \ 
      -port=5050 -sk=triangleIsBestFigure"
    ports: 
      - 5050:5050
    depends_on:
      - service.auth.db
    networks: 
      - authnet
    
networks: 
  authnet:
    driver: "bridge"