// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: protos/coursesservice/coursesservice.proto

package coursesservice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImgURL     string `protobuf:"bytes,3,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	ContentURL string `protobuf:"bytes,4,opt,name=contentURL,proto3" json:"contentURL,omitempty"` // TODO подумать о юрл контенте
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetImgURL() string {
	if x != nil {
		return x.ImgURL
	}
	return ""
}

func (x *Task) GetContentURL() string {
	if x != nil {
		return x.ContentURL
	}
	return ""
}

type TaskHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tasks []*Task `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *TaskHeader) Reset() {
	*x = TaskHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHeader) ProtoMessage() {}

func (x *TaskHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHeader.ProtoReflect.Descriptor instead.
func (*TaskHeader) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{1}
}

func (x *TaskHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskHeader) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Course struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImgURL      string        `protobuf:"bytes,3,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	TaskHeaders []*TaskHeader `protobuf:"bytes,4,rep,name=taskHeaders,proto3" json:"taskHeaders,omitempty"`
}

func (x *Course) Reset() {
	*x = Course{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{2}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetImgURL() string {
	if x != nil {
		return x.ImgURL
	}
	return ""
}

func (x *Course) GetTaskHeaders() []*TaskHeader {
	if x != nil {
		return x.TaskHeaders
	}
	return nil
}

// также токен будет передаваться с помощью клиенсктого интерсептора, парситься и из него в контексте передадут UID role и тд
//  courses  req/resp
type AddCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImgURL      string        `protobuf:"bytes,2,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	TaskHeaders []*TaskHeader `protobuf:"bytes,3,rep,name=taskHeaders,proto3" json:"taskHeaders,omitempty"`
}

func (x *AddCourseReq) Reset() {
	*x = AddCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCourseReq) ProtoMessage() {}

func (x *AddCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCourseReq.ProtoReflect.Descriptor instead.
func (*AddCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{3}
}

func (x *AddCourseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCourseReq) GetImgURL() string {
	if x != nil {
		return x.ImgURL
	}
	return ""
}

func (x *AddCourseReq) GetTaskHeaders() []*TaskHeader {
	if x != nil {
		return x.TaskHeaders
	}
	return nil
}

type AddCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO maybe add id of added course to resp
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddCourseResp) Reset() {
	*x = AddCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCourseResp) ProtoMessage() {}

func (x *AddCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCourseResp.ProtoReflect.Descriptor instead.
func (*AddCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{4}
}

func (x *AddCourseResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedCourse *Course `protobuf:"bytes,1,opt,name=updatedCourse,proto3" json:"updatedCourse,omitempty"`
}

func (x *UpdateCourseReq) Reset() {
	*x = UpdateCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseReq) ProtoMessage() {}

func (x *UpdateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseReq.ProtoReflect.Descriptor instead.
func (*UpdateCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCourseReq) GetUpdatedCourse() *Course {
	if x != nil {
		return x.UpdatedCourse
	}
	return nil
}

type UpdateCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCourseResp) Reset() {
	*x = UpdateCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResp) ProtoMessage() {}

func (x *UpdateCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResp.ProtoReflect.Descriptor instead.
func (*UpdateCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{6}
}

type DeleteCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCourseReq) Reset() {
	*x = DeleteCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseReq) ProtoMessage() {}

func (x *DeleteCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCourseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCourseResp) Reset() {
	*x = DeleteCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResp) ProtoMessage() {}

func (x *DeleteCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResp.ProtoReflect.Descriptor instead.
func (*DeleteCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{8}
}

type GetCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCourseReq) Reset() {
	*x = GetCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseReq) ProtoMessage() {}

func (x *GetCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseReq.ProtoReflect.Descriptor instead.
func (*GetCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetCourseReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Course *Course `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
}

func (x *GetCourseResp) Reset() {
	*x = GetCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResp) ProtoMessage() {}

func (x *GetCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResp.ProtoReflect.Descriptor instead.
func (*GetCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{10}
}

func (x *GetCourseResp) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetAllCoursesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllCoursesReq) Reset() {
	*x = GetAllCoursesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCoursesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoursesReq) ProtoMessage() {}

func (x *GetAllCoursesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoursesReq.ProtoReflect.Descriptor instead.
func (*GetAllCoursesReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{11}
}

type GetAllCoursesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
}

func (x *GetAllCoursesResp) Reset() {
	*x = GetAllCoursesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCoursesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCoursesResp) ProtoMessage() {}

func (x *GetAllCoursesResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCoursesResp.ProtoReflect.Descriptor instead.
func (*GetAllCoursesResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllCoursesResp) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

// TaskHeaders
type AddTaskHeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId   string      `protobuf:"bytes,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	TaskHeader *TaskHeader `protobuf:"bytes,2,opt,name=taskHeader,proto3" json:"taskHeader,omitempty"`
}

func (x *AddTaskHeaderReq) Reset() {
	*x = AddTaskHeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskHeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskHeaderReq) ProtoMessage() {}

func (x *AddTaskHeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskHeaderReq.ProtoReflect.Descriptor instead.
func (*AddTaskHeaderReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{13}
}

func (x *AddTaskHeaderReq) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AddTaskHeaderReq) GetTaskHeader() *TaskHeader {
	if x != nil {
		return x.TaskHeader
	}
	return nil
}

type AddTaskHeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddTaskHeaderResp) Reset() {
	*x = AddTaskHeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskHeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskHeaderResp) ProtoMessage() {}

func (x *AddTaskHeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskHeaderResp.ProtoReflect.Descriptor instead.
func (*AddTaskHeaderResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{14}
}

func (x *AddTaskHeaderResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTaskHeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskHeader *TaskHeader `protobuf:"bytes,2,opt,name=taskHeader,proto3" json:"taskHeader,omitempty"`
}

func (x *UpdateTaskHeaderReq) Reset() {
	*x = UpdateTaskHeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskHeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskHeaderReq) ProtoMessage() {}

func (x *UpdateTaskHeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskHeaderReq.ProtoReflect.Descriptor instead.
func (*UpdateTaskHeaderReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTaskHeaderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskHeaderReq) GetTaskHeader() *TaskHeader {
	if x != nil {
		return x.TaskHeader
	}
	return nil
}

type UpdateTaskHeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTaskHeaderResp) Reset() {
	*x = UpdateTaskHeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskHeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskHeaderResp) ProtoMessage() {}

func (x *UpdateTaskHeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskHeaderResp.ProtoReflect.Descriptor instead.
func (*UpdateTaskHeaderResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{16}
}

type DeleteTaskHeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTaskHeaderReq) Reset() {
	*x = DeleteTaskHeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskHeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskHeaderReq) ProtoMessage() {}

func (x *DeleteTaskHeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskHeaderReq.ProtoReflect.Descriptor instead.
func (*DeleteTaskHeaderReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteTaskHeaderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskHeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTaskHeaderResp) Reset() {
	*x = DeleteTaskHeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskHeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskHeaderResp) ProtoMessage() {}

func (x *DeleteTaskHeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskHeaderResp.ProtoReflect.Descriptor instead.
func (*DeleteTaskHeaderResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{18}
}

type AddTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskHeaderId string `protobuf:"bytes,1,opt,name=taskHeaderId,proto3" json:"taskHeaderId,omitempty"`
	Task         *Task  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *AddTaskReq) Reset() {
	*x = AddTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskReq) ProtoMessage() {}

func (x *AddTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskReq.ProtoReflect.Descriptor instead.
func (*AddTaskReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{19}
}

func (x *AddTaskReq) GetTaskHeaderId() string {
	if x != nil {
		return x.TaskHeaderId
	}
	return ""
}

func (x *AddTaskReq) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AddTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddTaskResp) Reset() {
	*x = AddTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskResp) ProtoMessage() {}

func (x *AddTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskResp.ProtoReflect.Descriptor instead.
func (*AddTaskResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{20}
}

func (x *AddTaskResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task *Task  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *UpdateTaskReq) Reset() {
	*x = UpdateTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskReq) ProtoMessage() {}

func (x *UpdateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskReq.ProtoReflect.Descriptor instead.
func (*UpdateTaskReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskReq) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTaskResp) Reset() {
	*x = UpdateTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResp) ProtoMessage() {}

func (x *UpdateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResp.ProtoReflect.Descriptor instead.
func (*UpdateTaskResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{22}
}

type DeleteTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTaskReq) Reset() {
	*x = DeleteTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskReq) ProtoMessage() {}

func (x *DeleteTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskReq.ProtoReflect.Descriptor instead.
func (*DeleteTaskReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTaskResp) Reset() {
	*x = DeleteTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResp) ProtoMessage() {}

func (x *DeleteTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResp.ProtoReflect.Descriptor instead.
func (*DeleteTaskResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{24}
}

type AddUserInCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseID string `protobuf:"bytes,1,opt,name=courseID,proto3" json:"courseID,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *AddUserInCourseReq) Reset() {
	*x = AddUserInCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserInCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserInCourseReq) ProtoMessage() {}

func (x *AddUserInCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserInCourseReq.ProtoReflect.Descriptor instead.
func (*AddUserInCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{25}
}

func (x *AddUserInCourseReq) GetCourseID() string {
	if x != nil {
		return x.CourseID
	}
	return ""
}

func (x *AddUserInCourseReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type AddUserInCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddUserInCourseResp) Reset() {
	*x = AddUserInCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserInCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserInCourseResp) ProtoMessage() {}

func (x *AddUserInCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserInCourseResp.ProtoReflect.Descriptor instead.
func (*AddUserInCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{26}
}

type DeleteUserInCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseID string `protobuf:"bytes,1,opt,name=courseID,proto3" json:"courseID,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *DeleteUserInCourseReq) Reset() {
	*x = DeleteUserInCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserInCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInCourseReq) ProtoMessage() {}

func (x *DeleteUserInCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteUserInCourseReq) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteUserInCourseReq) GetCourseID() string {
	if x != nil {
		return x.CourseID
	}
	return ""
}

func (x *DeleteUserInCourseReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteUserInCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserInCourseResp) Reset() {
	*x = DeleteUserInCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserInCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInCourseResp) ProtoMessage() {}

func (x *DeleteUserInCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coursesservice_coursesservice_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInCourseResp.ProtoReflect.Descriptor instead.
func (*DeleteUserInCourseResp) Descriptor() ([]byte, []int) {
	return file_protos_coursesservice_coursesservice_proto_rawDescGZIP(), []int{28}
}

var File_protos_coursesservice_coursesservice_proto protoreflect.FileDescriptor

var file_protos_coursesservice_coursesservice_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x04,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55,
	0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x52, 0x4c,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x55, 0x52, 0x4c,
	0x22, 0x4d, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22,
	0x73, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x6d, 0x67, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x6d, 0x67, 0x55, 0x52, 0x4c, 0x12, 0x2d, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x69, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55,
	0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x52, 0x4c,
	0x12, 0x2d, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22,
	0x1f, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x40, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f,
	0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22,
	0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x74,
	0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x74, 0x61,
	0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x73, 0x6b, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61,
	0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x1d, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x48, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x15, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0xcd, 0x05,
	0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x0d, 0x2e,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x10, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x33, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x12, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0d, 0x41, 0x64,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x0b, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x13, 0x2e, 0x41, 0x64,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x16, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_coursesservice_coursesservice_proto_rawDescOnce sync.Once
	file_protos_coursesservice_coursesservice_proto_rawDescData = file_protos_coursesservice_coursesservice_proto_rawDesc
)

func file_protos_coursesservice_coursesservice_proto_rawDescGZIP() []byte {
	file_protos_coursesservice_coursesservice_proto_rawDescOnce.Do(func() {
		file_protos_coursesservice_coursesservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_coursesservice_coursesservice_proto_rawDescData)
	})
	return file_protos_coursesservice_coursesservice_proto_rawDescData
}

var file_protos_coursesservice_coursesservice_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_protos_coursesservice_coursesservice_proto_goTypes = []interface{}{
	(*Task)(nil),                   // 0: Task
	(*TaskHeader)(nil),             // 1: TaskHeader
	(*Course)(nil),                 // 2: Course
	(*AddCourseReq)(nil),           // 3: AddCourseReq
	(*AddCourseResp)(nil),          // 4: AddCourseResp
	(*UpdateCourseReq)(nil),        // 5: UpdateCourseReq
	(*UpdateCourseResp)(nil),       // 6: UpdateCourseResp
	(*DeleteCourseReq)(nil),        // 7: DeleteCourseReq
	(*DeleteCourseResp)(nil),       // 8: DeleteCourseResp
	(*GetCourseReq)(nil),           // 9: GetCourseReq
	(*GetCourseResp)(nil),          // 10: GetCourseResp
	(*GetAllCoursesReq)(nil),       // 11: GetAllCoursesReq
	(*GetAllCoursesResp)(nil),      // 12: GetAllCoursesResp
	(*AddTaskHeaderReq)(nil),       // 13: AddTaskHeaderReq
	(*AddTaskHeaderResp)(nil),      // 14: AddTaskHeaderResp
	(*UpdateTaskHeaderReq)(nil),    // 15: UpdateTaskHeaderReq
	(*UpdateTaskHeaderResp)(nil),   // 16: UpdateTaskHeaderResp
	(*DeleteTaskHeaderReq)(nil),    // 17: DeleteTaskHeaderReq
	(*DeleteTaskHeaderResp)(nil),   // 18: DeleteTaskHeaderResp
	(*AddTaskReq)(nil),             // 19: AddTaskReq
	(*AddTaskResp)(nil),            // 20: AddTaskResp
	(*UpdateTaskReq)(nil),          // 21: UpdateTaskReq
	(*UpdateTaskResp)(nil),         // 22: UpdateTaskResp
	(*DeleteTaskReq)(nil),          // 23: DeleteTaskReq
	(*DeleteTaskResp)(nil),         // 24: DeleteTaskResp
	(*AddUserInCourseReq)(nil),     // 25: AddUserInCourseReq
	(*AddUserInCourseResp)(nil),    // 26: AddUserInCourseResp
	(*DeleteUserInCourseReq)(nil),  // 27: DeleteUserInCourseReq
	(*DeleteUserInCourseResp)(nil), // 28: DeleteUserInCourseResp
}
var file_protos_coursesservice_coursesservice_proto_depIdxs = []int32{
	0,  // 0: TaskHeader.tasks:type_name -> Task
	1,  // 1: Course.taskHeaders:type_name -> TaskHeader
	1,  // 2: AddCourseReq.taskHeaders:type_name -> TaskHeader
	2,  // 3: UpdateCourseReq.updatedCourse:type_name -> Course
	2,  // 4: GetCourseResp.course:type_name -> Course
	2,  // 5: GetAllCoursesResp.courses:type_name -> Course
	1,  // 6: AddTaskHeaderReq.taskHeader:type_name -> TaskHeader
	1,  // 7: UpdateTaskHeaderReq.taskHeader:type_name -> TaskHeader
	0,  // 8: AddTaskReq.task:type_name -> Task
	0,  // 9: UpdateTaskReq.task:type_name -> Task
	3,  // 10: CoursesService.AddCourse:input_type -> AddCourseReq
	5,  // 11: CoursesService.UpdateCourse:input_type -> UpdateCourseReq
	7,  // 12: CoursesService.DeleteCourse:input_type -> DeleteCourseReq
	9,  // 13: CoursesService.GetCourse:input_type -> GetCourseReq
	11, // 14: CoursesService.GetAllCourses:input_type -> GetAllCoursesReq
	13, // 15: CoursesService.AddTaskHeader:input_type -> AddTaskHeaderReq
	15, // 16: CoursesService.UpdateTaskHeader:input_type -> UpdateTaskHeaderReq
	17, // 17: CoursesService.DeleteTaskHeader:input_type -> DeleteTaskHeaderReq
	19, // 18: CoursesService.AddTask:input_type -> AddTaskReq
	21, // 19: CoursesService.UpdateTask:input_type -> UpdateTaskReq
	23, // 20: CoursesService.DeleteTask:input_type -> DeleteTaskReq
	25, // 21: CoursesService.AddUserInCourse:input_type -> AddUserInCourseReq
	27, // 22: CoursesService.DeleteUserInCourse:input_type -> DeleteUserInCourseReq
	4,  // 23: CoursesService.AddCourse:output_type -> AddCourseResp
	6,  // 24: CoursesService.UpdateCourse:output_type -> UpdateCourseResp
	8,  // 25: CoursesService.DeleteCourse:output_type -> DeleteCourseResp
	10, // 26: CoursesService.GetCourse:output_type -> GetCourseResp
	12, // 27: CoursesService.GetAllCourses:output_type -> GetAllCoursesResp
	14, // 28: CoursesService.AddTaskHeader:output_type -> AddTaskHeaderResp
	16, // 29: CoursesService.UpdateTaskHeader:output_type -> UpdateTaskHeaderResp
	18, // 30: CoursesService.DeleteTaskHeader:output_type -> DeleteTaskHeaderResp
	20, // 31: CoursesService.AddTask:output_type -> AddTaskResp
	22, // 32: CoursesService.UpdateTask:output_type -> UpdateTaskResp
	24, // 33: CoursesService.DeleteTask:output_type -> DeleteTaskResp
	26, // 34: CoursesService.AddUserInCourse:output_type -> AddUserInCourseResp
	28, // 35: CoursesService.DeleteUserInCourse:output_type -> DeleteUserInCourseResp
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_coursesservice_coursesservice_proto_init() }
func file_protos_coursesservice_coursesservice_proto_init() {
	if File_protos_coursesservice_coursesservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_coursesservice_coursesservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Course); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCoursesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCoursesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskHeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskHeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskHeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskHeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskHeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskHeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserInCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserInCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserInCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_coursesservice_coursesservice_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserInCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_coursesservice_coursesservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_coursesservice_coursesservice_proto_goTypes,
		DependencyIndexes: file_protos_coursesservice_coursesservice_proto_depIdxs,
		MessageInfos:      file_protos_coursesservice_coursesservice_proto_msgTypes,
	}.Build()
	File_protos_coursesservice_coursesservice_proto = out.File
	file_protos_coursesservice_coursesservice_proto_rawDesc = nil
	file_protos_coursesservice_coursesservice_proto_goTypes = nil
	file_protos_coursesservice_coursesservice_proto_depIdxs = nil
}
